apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spalabfinal-restapi
  labels:
    app: spalabfinalexam
    tier: restapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: spalabfinal
        tier: restapi
    spec:
      containers:
      - name: spalabfinalexam-app
        image: gcr.io/decoded-carport-203407/spalabfinalexam:latest
        command: ["spa-lab-final-exam"]
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8000